### ISSUE TITLE
Dependency to notify-send.sh

### ISSUE THREAD

**Issue by madic-creates** [sentriz/wl-gammactld#1]
Without a script called notify-send.sh this script does not work. I assume it's this one? https://github.com/vlevit/notify-send.sh

**Comment by sentriz** [comment]
Hey

You can find the script here
https://github.com/vlevit/notify-send.sh

It's useful since it provides the --replace-file argument (for seamless brightness notifications) unlike the traditional notify-send

If you only have notify-send you could drop the .sh and --replace-file 

On 1 February 2021 21:59:09 GMT, Madic- <notifications@github.com> wrote:
>Without a script called notify-send.sh this script does not work
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sentriz/wl-gammactld/issues/1
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by madic-creates** [comment]
Ok. Thank you for your help and your script
